# Generated by Django 3.2.5 on 2021-08-21 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_user', models.CharField(blank=True, max_length=20, null=True)),
                ('contact_user_id', models.CharField(blank=True, max_length=20, null=True)),
                ('contact_user_email', models.EmailField(max_length=254)),
                ('conatact_user_phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.TextField()),
            ],
        ),
    ]
