# Generated by Django 3.2.5 on 2021-08-21 15:51

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20210821_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='user',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name=django.contrib.auth.models.User),
        ),
    ]
