# Generated by Django 3.2.5 on 2021-08-21 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_alter_contactform_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='user',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
