# Generated by Django 3.2.5 on 2021-08-24 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_alter_contactform_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactform',
            name='userid',
        ),
    ]
