# Generated by Django 3.2.5 on 2021-08-24 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_remove_contactform_userid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactform',
            name='user',
        ),
        migrations.AddField(
            model_name='contactform',
            name='user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.userprofile'),
        ),
    ]
