# Generated by Django 3.2.5 on 2021-08-24 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_auto_20210824_1508'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactform',
            old_name='user_profile',
            new_name='user',
        ),
    ]
