# Generated by Django 3.2.5 on 2021-08-24 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_rename_user_profile_contactform_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactForm',
        ),
    ]
