# Generated by Django 3.2.5 on 2021-08-25 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_contactform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactform',
            name='user',
        ),
        migrations.AddField(
            model_name='contactform',
            name='user_username',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
